import type { Config } from "tailwindcss"

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["\"Plus Jakarta Sans\"", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      colors: {
        "bg-app": "rgb(var(--bg-app) / <alpha-value>)",
        panel: "rgb(var(--panel) / <alpha-value>)",
        "panel-muted": "rgb(var(--panel-muted) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        "border-strong": "rgb(var(--border-strong) / <alpha-value>)",
        text: "rgb(var(--text) / <alpha-value>)",
        "text-muted": "rgb(var(--text-muted) / <alpha-value>)",
        "text-subtle": "rgb(var(--text-subtle) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        "accent-strong": "rgb(var(--accent-strong) / <alpha-value>)",
        "accent-contrast": "rgb(var(--accent-contrast) / <alpha-value>)",
        focus: "rgb(var(--focus) / <alpha-value>)",
        "warning-soft": "rgb(var(--warning-soft) / <alpha-value>)",
        "warning-border": "rgb(var(--warning-border) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        "danger-soft": "rgb(var(--danger-soft) / <alpha-value>)",
        "event-exam": "rgb(var(--event-exam) / <alpha-value>)",
        "event-exam-soft": "rgb(var(--event-exam-soft) / <alpha-value>)",
        "event-exam-border": "rgb(var(--event-exam-border) / <alpha-value>)",
        "event-class": "rgb(var(--event-class) / <alpha-value>)",
        "event-class-soft": "rgb(var(--event-class-soft) / <alpha-value>)",
        "event-class-border": "rgb(var(--event-class-border) / <alpha-value>)",
        "event-deadline": "rgb(var(--event-deadline) / <alpha-value>)",
        "event-deadline-soft": "rgb(var(--event-deadline-soft) / <alpha-value>)",
        "event-deadline-border": "rgb(var(--event-deadline-border) / <alpha-value>)",
        "event-assignment": "rgb(var(--event-assignment) / <alpha-value>)",
        "event-assignment-soft": "rgb(var(--event-assignment-soft) / <alpha-value>)",
        "event-assignment-border": "rgb(var(--event-assignment-border) / <alpha-value>)",
        "event-quiz": "rgb(var(--event-quiz) / <alpha-value>)",
        "event-quiz-soft": "rgb(var(--event-quiz-soft) / <alpha-value>)",
        "event-quiz-border": "rgb(var(--event-quiz-border) / <alpha-value>)",
        "event-project": "rgb(var(--event-project) / <alpha-value>)",
        "event-project-soft": "rgb(var(--event-project-soft) / <alpha-value>)",
        "event-project-border": "rgb(var(--event-project-border) / <alpha-value>)",
        "event-reading": "rgb(var(--event-reading) / <alpha-value>)",
        "event-reading-soft": "rgb(var(--event-reading-soft) / <alpha-value>)",
        "event-reading-border": "rgb(var(--event-reading-border) / <alpha-value>)",
        "event-lecture": "rgb(var(--event-lecture) / <alpha-value>)",
        "event-lecture-soft": "rgb(var(--event-lecture-soft) / <alpha-value>)",
        "event-lecture-border": "rgb(var(--event-lecture-border) / <alpha-value>)",
        "event-presentation": "rgb(var(--event-presentation) / <alpha-value>)",
        "event-presentation-soft": "rgb(var(--event-presentation-soft) / <alpha-value>)",
        "event-presentation-border": "rgb(var(--event-presentation-border) / <alpha-value>)",
        "event-meeting": "rgb(var(--event-meeting) / <alpha-value>)",
        "event-meeting-soft": "rgb(var(--event-meeting-soft) / <alpha-value>)",
        "event-meeting-border": "rgb(var(--event-meeting-border) / <alpha-value>)",
        "event-other": "rgb(var(--event-other) / <alpha-value>)",
        "event-other-soft": "rgb(var(--event-other-soft) / <alpha-value>)",
        "event-other-border": "rgb(var(--event-other-border) / <alpha-value>)",
        "confidence-high": "rgb(var(--confidence-high) / <alpha-value>)",
        "confidence-high-soft": "rgb(var(--confidence-high-soft) / <alpha-value>)",
        "confidence-high-border": "rgb(var(--confidence-high-border) / <alpha-value>)",
        "confidence-medium": "rgb(var(--confidence-medium) / <alpha-value>)",
        "confidence-medium-soft": "rgb(var(--confidence-medium-soft) / <alpha-value>)",
        "confidence-medium-border": "rgb(var(--confidence-medium-border) / <alpha-value>)",
        "confidence-low": "rgb(var(--confidence-low) / <alpha-value>)",
        "confidence-low-soft": "rgb(var(--confidence-low-soft) / <alpha-value>)",
        "confidence-low-border": "rgb(var(--confidence-low-border) / <alpha-value>)",
        overlay: "rgb(var(--overlay) / <alpha-value>)",
        ink: "#123B39",
        teal: {
          50: "#F0FDFA",
          100: "#CCFBF1",
          500: "#14B8A6",
          600: "#0D9488",
          700: "#0F766E",
          800: "#115E59"
        },
        warning: {
          DEFAULT: "rgb(var(--warning) / <alpha-value>)",
          50: "#FFF7ED",
          100: "#FFEDD5",
          500: "#F97316",
          700: "#C2410C"
        }
      },
      boxShadow: {
        panel: "0 1px 2px rgba(15, 23, 42, 0.04), 0 12px 30px rgba(15, 118, 110, 0.06)",
      },
    },
  },
  plugins: [],
} satisfies Config
